export const ENTITIES_ACTIONS = {
  SAVE: "ENTITIES.SAVE",
  REMOVE: "ENTITIES.REMOVE"
};

export const PRODUCT_ACTIONS = {
  FETCH_REQUEST: "PRODUCT.FETCH_REQUEST",
  FETCH_SUCCESS: "PRODUCT.FETCH_SUCCESS",
  FETCH_FAILURE: "PRODUCT.FETCH_FAILURE",

  FETCH_LIST_REQUEST: "PRODUCT.FETCH_LIST_REQUEST",
  FETCH_LIST_SUCCESS: "PRODUCT.FETCH_LIST_SUCCESS",
  FETCH_LIST_FAILURE: "PRODUCT.FETCH_LIST_FAILURE",
  
  UPDATE_REQUEST: "PRODUCT.UPDATE_REQUEST",
  UPDATE_SUCCESS: "PRODUCT.UPDATE_SUCCESS",
  UPDATE_FAILURE: "PRODUCT.UPDATE_FAILURE",
  
  REPLACE_REQUEST: "PRODUCT.REPLACE_REQUEST",
  REPLACE_SUCCESS: "PRODUCT.REPLACE_SUCCESS",
  REPLACE_FAILURE: "PRODUCT.REPLACE_FAILURE",
  
  CREATE_REQUEST: "PRODUCT.CREATE_REQUEST",
  CREATE_SUCCESS: "PRODUCT.CREATE_SUCCESS",
  CREATE_FAILURE: "PRODUCT.CREATE_FAILURE",
  
  DELETE_REQUEST: "PRODUCT.DELETE_REQUEST",
  DELETE_SUCCESS: "PRODUCT.DELETE_SUCCESS",
  DELETE_FAILURE: "PRODUCT.DELETE_FAILURE",

  RESET: "PRODUCT.RESET",
};

export const CATEGORY_ACTIONS = {
  FETCH_REQUEST: "CATEGORY.FETCH_REQUEST",
  FETCH_SUCCESS: "CATEGORY.FETCH_SUCCESS",
  FETCH_FAILURE: "CATEGORY.FETCH_FAILURE",

  FETCH_LIST_REQUEST: "CATEGORY.FETCH_LIST_REQUEST",
  FETCH_LIST_SUCCESS: "CATEGORY.FETCH_LIST_SUCCESS",
  FETCH_LIST_FAILURE: "CATEGORY.FETCH_LIST_FAILURE",
  
  RESET: "CATEGORY.RESET",
};

export const CART_ACTIONS = {
  FETCH_REQUEST: "CART.FETCH_REQUEST",
  FETCH_SUCCESS: "CART.FETCH_SUCCESS",
  FETCH_FAILURE: "CART.FETCH_FAILURE",

  FETCH_LIST_REQUEST: "CART.FETCH_LIST_REQUEST",
  FETCH_LIST_SUCCESS: "CART.FETCH_LIST_SUCCESS",
  FETCH_LIST_FAILURE: "CART.FETCH_LIST_FAILURE",

  RESET: "CART.RESET"
};

export const SESSION_ACTIONS = {
  FETCH_USER_REQUEST: "SESSION_ACTIONS.FETCH_USER_REQUEST",
  FETCH_USER_SUCCESS: "SESSION_ACTIONS.FETCH_USER_SUCCESS",
  FETCH_USER_FAILURE: "SESSION_ACTIONS.FETCH_USER_FAILURE",

  RESET_USER: "SESSION_ACTIONS.RESET_USER",

  FETCH_SHOP_REQUEST: "SESSION_ACTIONS.FETCH_SHOP_REQUEST",
  FETCH_SHOP_SUCCESS: "SESSION_ACTIONS.FETCH_SHOP_SUCCESS",
  FETCH_SHOP_FAILURE: "SESSION_ACTIONS.FETCH_SHOP_FAILURE",

  RESET_SHOP: "SESSION_ACTIONS.RESET_SHOP"
};

export const AUTH_ACTIONS = {
  CREATE_TOKEN_REQUEST: "AUTH.CREATE_TOKEN_REQUEST",
  CREATE_TOKEN_SUCCESS: "AUTH.CREATE_TOKEN_SUCCESS",
  CREATE_TOKEN_FAILURE: "AUTH.CREATE_TOKEN_FAILURE",

  CHECK_TOKEN_REQUEST: "AUTH.CHECK_TOKEN_REQUEST",
  CHECK_TOKEN_SUCCESS: "AUTH.CHECK_TOKEN_SUCCESS",
  CHECK_TOKEN_FAILURE: "AUTH.CHECK_TOKEN_FAILURE"
};

export const ERRORS_ACTIONS = {
  SAVE_API_ERROR: "ERRORS.SAVE_API_ERROR"
};
